### ISSUE TITLE
Admin cannot edit content by default

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/cwp#114]
Using `cwp-recipe-kitchen-sink` `2.1.x-dev`. 

As an admin, I can save and publish content, but I cannot actually modify any content:

![image](https://user-images.githubusercontent.com/14869519/41564715-d5b8f256-73a7-11e8-9768-e724fa9999d4.png)

The issue persists, even when turning of content review and workflow via the settings section of the page.

**Comment by robbieaverill** [comment]
Context: CWP 2.0.x has advancedworkflow 5.0.6, CWP 2.1.x has 5.0.x-dev

The difference is [almost nothing](https://github.com/symbiote/silverstripe-advancedworkflow/compare/5.0.6...5.0) which indicates that this issue might not be caused by changes in that module but changes in core that support its functionality.

**Comment by robbieaverill** [comment]
I wonder if this could be caused by missing assets. I'm seeing the same thing in content blocks:

![image](https://user-images.githubusercontent.com/5170590/41566252-da54faf6-73ae-11e8-90be-c10a8cf139f2.png)

**Comment by robbieaverill** [comment]
Fix at #116
