### ISSUE TITLE
No styling applied to BasePage inheritants

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/cwp#67]
Neither when using the simple nor the starter themes are any templates loaded to pages that extend from the CWP page type `BasePage`.

This appears to be a regression from 1.8.1 where styles were provided for this page type.

**Comment by robbieaverill** [comment]
Hey @raissanorth and @antons-, thanks for reporting this issue.

I've had a quick look at this, and you're right in that if you extend BasePage then you won't get any templates. This is because BasePage extends the CMS module's SiteTree model directly, which doesn't have any templates. Theme templates are centered around the Page class.

Please extend `Page` rather than BasePage. Page already extends BasePage, which is designed to provide some additional functionality to all pages in a CWP website by getting in between the regular SilverStripe inheritance which is Page extends SiteTree. Not including Page in your class hierarchy could lead to unintended side effects since many CMS related SilverStripe modules rely on a Page class being involved.

I've submitted a pull request at #70 to clarify the BasePage docs a little in hope of avoiding this coming up again in future.

Thanks!
