### ISSUE TITLE
Missing macron on spellcheck feature

### ISSUE THREAD

**Issue by katieelks** [silverstripe/cwp#84]
On a content block, the spellcheck gives two options:

- English (New Zealand)
- Maori (New Zealand)

The second option should be:

- Māori (New Zealand)

**Comment by robbieaverill** [comment]
Tricky. This langauge name comes from the PHP Intl extension, which we don't have the ability to fix (at least immediately). We can probably do a search and replace for `Maori` -> `Māori` in the `SpellCheckMiddleware::getLanguages()` method though, which would be a temporary fix.

**Comment by katieelks** [comment]
yeah - low priority but said I would pass it on :)

**Comment by robbieaverill** [comment]
@katieelks this problem is not entirely fixed, in that the origin of the misspelling is the PHP intl extension which is outside our scope to fix, but we've fixed it in the list of languages you get when you install SilverStripe (https://github.com/silverstripe/silverstripe-framework/pull/8089) and manually patched it when using the spellchecker in the CMS (https://github.com/silverstripe/silverstripe-spellcheck/pull/37). Both changes will be in CWP 2.1.0 in a few weeks.
